http:
  routers:
    # Frontend - highest priority for root path
    frontend:
      rule: "Host(`matcha.bombatomica64.dev`) && PathPrefix(`/`)"
      service: frontend-service
      entryPoints:
        - web
      middlewares:
        - default-headers
      priority: 1  # Lowest priority for catch-all

    # Backend API routes
    backend-api:
      rule: "Host(`matcha.bombatomica64.dev`) && PathPrefix(`/api`)"
      service: backend-service
      entryPoints:
        - web
      middlewares:
        - api-stripprefix
        - default-headers
        - cors-headers
      priority: 3  # Higher priority for API
    
    # Socket.IO routes - with HTTP/3 support for WebTransport
    backend-socketio:
      rule: "Host(`matcha.bombatomica64.dev`) && PathPrefix(`/socket.io`)"
      service: backend-service
      entryPoints:
        - web
        - websecure
      middlewares:
        - default-headers
        - cors-headers
        - http3-headers
      priority: 2  # High priority for Socket.IO

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:3000"
        sticky:
          cookie:
            name: "backend"
    
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:4200"

  # Middlewares
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        accessControlAllowOriginList:
          - "*"
    
    api-stripprefix:
      stripPrefix:
        prefixes:
          - "/api"
    
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        customResponseHeaders:
          Access-Control-Allow-Origin: "*"
          Access-Control-Allow-Credentials: "true"
    
    http3-headers:
      headers:
        customResponseHeaders:
          Alt-Svc: 'h3=":443"; ma=86400'

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"