http:
  routers:
    # Frontend served on main host
    frontend:
      rule: "Host(`matcha.bombatomica64.dev`)"
      service: frontend-service
      entryPoints:
        - web
        - websecure
      middlewares:
        - default-headers
      priority: 1

    # Backend served on api subdomain
    backend:
      rule: "Host(`api.matcha.bombatomica64.dev`)"
      service: backend-service
      entryPoints:
        - web
        - websecure
      middlewares:
        - default-headers
        - cors-headers
      priority: 2

    # Socket.IO on backend host (optional explicit routing)
    backend-socketio:
      rule: "Host(`api.matcha.bombatomica64.dev`) && PathPrefix(`/socket.io`)"
      service: backend-service
      entryPoints:
        - web
        - websecure
      middlewares:
        - default-headers
        - cors-headers
        - http3-headers
      priority: 3

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:3000"
        sticky:
          cookie:
            name: "backend"
    
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:4200"

  # Middlewares
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        accessControlAllowOriginList:
          - "https://matcha.bombatomica64.dev"
    
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowCredentials: true
        accessControlAllowOriginList:
          - "https://matcha.bombatomica64.dev"
    
    http3-headers:
      headers:
        customResponseHeaders:
          Alt-Svc: 'h3=":443"; ma=86400'

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"