SELECT id,
       username,
       email,
       birth_date,
       password,
       bio,
       first_name,
       last_name,
       activated,
       profile_complete,
       gender,
       sexual_orientation,
       location,
       location_manual,
       fame_rating,
       last_seen,
       online_status,
       email_verification_token,
       email_verified_at,
       password_reset_token,
       password_reset_expires_at,
       likes_received_count,
       views_count,
       matches_count,
       created_at,
       updated_at
FROM public.users
LIMIT 1000;